 # giacase=input('nhập giá dịch vụ:  ')
        # tinhtrnghonnhan=input('Nhập tình trạng hôn nhân nha:  ')
        # print(' trong vòng 14 ngày anh chị có : ')
        # benh=input('có nghi ngờ mình bị covid-19 hay k: ')
        # tiepxuc=input('Tiếp xúc với bệnh nhân nghi ngờ là F0 hay không: ')
        # vungdich=input('có đi từ vùng dịch về khopong: ')
        # print('trong vòng 14 ngày anh chị có xuất hiện dấu hiệu nào sau đây:')
        # sot=input('bạn có bị sốt hay không: ')
        # ho=input('bạn có bị ho hay không: ')
        # khotho=input('bạn có khó thở hay không: ')
        # dauhong=input('bạn có đau họng hay không: ')
        # metmoi=input('bạn có mệt mỏi hay không: ')
        # benhnen=input('bệnh nền của anh chị là gì nhỉ: ')
